export enum ACTION {
    CHANGE_TAB="CHANGE_TAB",
    ON_SEARCH_LEADS="ON_SEARCH_LEADS",
    ON_SELECT="ON_SELECT",
    ON_SORT="ON_SORT",
    ON_SELECT_ALL_LEADS = 'ON_SELECT_ALL_LEADS',
    ON_LOAD = 'ON_LOAD',
    CHANGE_INPUT_AC="CHANGE_INPUT_AC",
    ON_SEARCH_AC="ON_SEARCH_AC",
    ON_SELECT_AC="ON_SELECT_AC",
    ON_SORT_AC="ON_SORT_AC",
    ON_SELECT_ALL_AC = 'ON_SELECT_ALL_AC',
    ON_FILTER_LEADS_BY_STATUS = 'ON_FILTER_LEADS_BY_STATUS',
}

