export const mock = {
  isLoggedIn: true,
  user: {
    userId: "05aa50d6-80ae-4ff5-8647-b053b447c8fc",
    phoneNumber: "+918763666620",
    emailId: null,
    fullName: null,
    gender: null,
    address: null,
    onboardingPartnerCode: null,
    onboardingRelationshipManagerCode: null,
    state: "ACTIVE",
    externalId: null,
    isInternal: null,
    addedOnTimeStamp: 1665813910221,
    lastUpdatedTimeStamp: 1665813910221,
  },
  linkedBorrowerAccounts: [
    {
      "@type": "Borrower",
      accountId: "16f3aa4c-2131-4cdd-bd58-8ca49f8f7b8b",
      accountState: "ACTIVE",
      isInternal: false,
      accountTier: "BASIC",
      addedOnTimeStamp: 1665813910243,
      lastUpdatedTimeStamp: 1665985278928,
      accountHolderPhoneNumber: "+918763666620",
      accountHolderEmail: "soumya.sethy@voltmoney.in",
      isKYCVerified: null,
      isBankAccountVerified: null,
    },
  ],
  linkedPartnerAccounts: [],
  linkedPlatformAccounts: [
    {
      "@type": "Platform",
      accountId: "6a8d1b14-61fc-4b30-ad07-de4052b4f295",
      accountState: "ACTIVE",
      isInternal: false,
      accountTier: "BASIC",
      addedOnTimeStamp: 1665751958715,
      lastUpdatedTimeStamp: 1665751959014,
      platformName: "Platform 1",
      platformLogoImgSrc: "wGTIRwOTOncrw2GIstss",
      platformCode: "VOLT_MOBILE_APP",
      platformAgreementIdUri: null,
      address: "UFdIMRVvZaJkUamfyCYoiGHaHcmSdA",
    },
  ],
  linkedApplications: [
    {
      applicationId: "8439968d-f996-44dd-a1e1-e3d25865bd47",
      externalId: null,
      accountId: "16f3aa4c-2131-4cdd-bd58-8ca49f8f7b8b",
      applicationType: "CREDIT_AGAINST_SECURITIES",
      applicationState: "IN_PROGRESS",
      applicationApprovalStatus: null,
      creditAmount: null,
      currentStepId: "MF_PLEDGING",
      stepStatusMap: {
        KYC_PHOTO_VERIFICATION: "NOT_STARTED",
        MF_PLEDGING: "NOT_STARTED",
        CREDIT_APPROVAL: "NOT_STARTED",
        KYC_AADHAAR_VERIFICATION: "NOT_STARTED",
        MANDATE_SETUP: "NOT_STARTED",
        KYC_CKYC: "NOT_STARTED",
        KYC_PAN_VERIFICATION: "COMPLETED",
        AGREEMENT_SIGN: "NOT_STARTED",
        BANK_ACCOUNT_VERIFICATION: "NOT_STARTED",
      },
      createdOn: 1665813910930,
      lastUpdatedOn: 1666071355780,
      completedOn: null,
    },
  ],
  linkedCredits: [],
};
