export enum ACTION {
  ONCHANGE_BANK_NAME = "ONCHANGE_BANK_NAME",
  ONCHANGE_ACCOUNT_NUMBER = "ONCHANGE_ACCOUNT_NUMBER",
  ONCHANGE_CONFIRM_ACCOUNT_NUMBER = "ONCHANGE_CONFIRM_ACCOUNT_NUMBER",
  NAVIGATION_SEARCH_IFSC = "NAVIGATION_SEARCH_IFSC",
  ONCHANGE_IFSC = "ONCHANGE_IFSC",
  ONCHANGE_BANK_DETAILS="ONCHANGE_BANK_DETAILS",
  ONCHANGE_IFSC_NUMBER = "ONCHANGE_IFSC_NUMBER",
  TRIGGER_CTA = "TRIGGER_CTA",
  TOGGLE_CTA = "TOGGLE_CTA",
  CHANGE_BANK_GO_BACK = "CHANGE_BANK_GO_BACK",
  NAV_STEPPER = "NAV_STEPPER",
  GO_NEXT = "GO_BACK",
}
export type NavigationSearchIFSCActionPayload = {
  bankCode: string;
  bankName: string;
};
export type InputNumberActionPayload = { value: string };
export type BAVVerifyActionPayload = {
  applicationId: string;
};