export const BanksRepo = {
  ALLBANKS: {
    AJAR: "Ajara Urban Co-operative Bank",
    MDBK: "Model Co-operative Bank",
    JPCB: "Jalgaon Peoples Co-operative Bank",
    ANZB: "Australia and New Zealand Banking Group",
    DEOB: "Deogiri Nagari Sahakari Bank Aurangabad",
    SURY: "Suryoday Small Finance Bank",
    MDCB: "Mumbai District Central Co-operative Bank",
    BDBL: "Bandhan Bank",
    MCAB: "Meghalaya Co-operative Apex Bank",
    SUSB: "Suco Souharda Sahakari Bank",
    SECB: "Sree Charan Souhardha Co-operative Bank",
    IBKL: "IDBI",
    APMC: "A.P. Mahesh Co-operative Urban Bank",
    KACE: "Kangra Central Co-operative Bank",
    SOGE: "Societe Generale",
    UPCB: "Uttar Pradesh Co-operative Bank",
    FIRN: "Firstrand Bank",
    IBKO: "Industrial Bank of Korea",
    SMCB: "Shivalik Small Finance Bank",
    CRLY: "Credit Agricole Corporate and Investment Bank",
    ARBL: "Arvind Sahakari Bank",
    KARB: "Karnataka Bank",
    SVCB: "SVC Co-operative Bank",
    SKNB: "Shree Kadi Nagarik Sahakari Bank",
    UJVN: "Ujjivan Small Finance Bank",
    NNSB: "Nutan Nagarik Sahakari Bank",
    SBLS: "Samarth Sahakari Bank",
    VARA: "Varachha Co-operative Bank",
    PKGB: "Karnataka Gramin Bank",
    MKPB: "Malkapur Urban Co-operative Bank",
    RDCB: "Rajnandgaon District Central Co-operative Bank",
    ICLL: "Indian Clearing Corporation",
    SMBC: "Sumitomo Mitsui Banking Corporation",
    HUSB: "Hutatma Sahakari Bank",
    INDB: "Indusind Bank",
    NUCB: "Nagar Urban Co-operative Bank",
    MCBL: "Mahanagar Co-operative Bank",
    RSCB: "Rajasthan State Co-operative Bank",
    BCBM: "Bharat Co-operative Bank",
    NSPB: "NSDL Payments Bank",
    MSBL: "Malad Sahakari Bank",
    SDCE: "Satara District Central Co-operative Bank",
    UBIN: "Union Bank of India",
    SDCB: "Surat District Co-operative Bank",
    GBCB: "Greater Bombay Co-operative Bank",
    PUNB: "Punjab National Bank",
    UTKS: "Utkarsh Small Finance Bank",
    PYTM: "Paytm Payments Bank",
    FSFB: "Fincare Small Finance Bank",
    GSCB: "Gujarat State Co-operative Bank",
    VASJ: "Vasai Janata Sahakari Bank",
    CLBL: "Capital Small Finance Bank",
    RSBL: "Rajgurunagar Sahakari Bank",
    TNSC: "Tamilnadu State Apex Co-operative Bank",
    NESF: "North East Small Finance Bank",
    RMGB: "Rajasthan Marudhara Gramin Bank",
    YESB: "Yes Bank",
    WBSC: "West Bengal State Co-operative Bank",
    RSSB: "Rajarshi Shahu Sahakari Bank",
    SUTB: "Sutex Co-operative Bank",
    AIRP: "Airtel Payments Bank",
    DNSB: "Dombivli Nagari Sahakari Bank",
    PSIB: "Punjab & Sind Bank",
    NMCB: "Nasik Merchants Co-operative Bank",
    TNCB: "Nawanagar Co-operative Bank",
    SKSB: "Shikshak Sahakari Bank",
    BKDN: "Dena Bank",
    CTCB: "Chinatrust Commercial Bank",
    ITBL: "Irinjalakuda Town Co-operative Bank",
    HDFC: "HDFC Bank",
    RABO: "Rabobank International",
    EBIL: "Emirates NBD Bank",
    TBMC: "Banaskantha Mercantile Co-operative Bank",
    HCBL: "HASTI Co-operative Bank",
    TMBL: "Tamilnad Mercantile Bank",
    CSBK: "Catholic Syrian Bank",
    DURG: "Durgapur Steel Peoples Co-operative Bank",
    STCB: "SBM Bank",
    APBL: "Andhra Pradesh State Co-operative Bank",
    MSCI: "Maharashtra State Co-operative Bank",
    RRBP: "Rajarambapu Sahakari Bank",
    BCEY: "Bank of Ceylon",
    HSBC: "Hongkong & Shanghai Banking Corporation",
    BARC: "Barclays Bank",
    TMSB: "The Malad Sahakari Bank",
    BARA: "Baramati Sahakari Bank",
    BARB: "Bank of Baroda",
    SANT: "Sant Sopankaka Sahakari Bank",
    NTBL: "Nainital Bank",
    CCBL: "Citizen Credit Co-operative Bank",
    SCBL: "Standard Chartered Bank",
    SYNB: "Syndicate Bank",
    BACB: "Bassein Catholic Co-operative Bank",
    SJSB: "Solapur Janata Sahakari Bank",
    ICBK: "Industrial and Commercial Bank of China",
    LAVB: "Laxmi Vilas Bank",
    NBRD: "National Bank for Agriculture and Development",
    TSAB: "Telangana State Co-operative Apex Bank",
    HARC: "Haryana State Co-operative Apex Bank",
    KBKB: "Kookmin Bank",
    RATN: "RBL Bank",
    KNSB: "Kurla Nagarik Sahakari Bank",
    IDUK: "Idukki District Co-operative Bank",
    KAIJ: "Kallappanna Awade Ichalkaranji Janata Sahakari Bank",
    KVBL: "Karur Vysya Bank",
    SRCB: "Saraswat Co-operative Bank",
    UUCB: "Udaipur Urban Co-operative Bank",
    CSBX: "Chartered Sahakari Bank Niyamitha",
    UOVB: "United Overseas Bank",
    DOHB: "Doha Bank QSC",
    ESMF: "Esaf Small Finance Bank",
    TDCB: "Thane District Central Co-operative Bank",
    ABHY: "Abhyudaya Co-operative Bank",
    JAKA: "Jammu and Kashmir Bank",
    NBAD: "National Bank of Abu Dhabi PJSC",
    AHDC: "Ahmednagar District Central Co-operative Bank",
    DLSC: "Delhi State Co-operative Bank",
    TTCB: "Textile Traders Co-operative Bank",
    AJHC: "Ambarnath Jai-hind Co-operative Bank",
    AKJB: "Akola Janata Commercial Co-operative Bank",
    ALLA: "Allahabad Bank",
    DEUT: "Deutsche Bank",
    IBBK: "PT Bank Maybank Indonesia TBK",
    PUCB: "Pandharpur Urban Co-operative Bank",
    UTBI: "United Bank of India",
    VIJB: "Vijaya Bank",
    SIBL: "South Indian Bank",
    JANA: "Janaseva Sahakari Bank, Pune",
    MSHQ: "Mashreq Bank",
    DCBL: "DCB Bank",
    TBSB: "Thane Bharat Sahakari Bank",
    ZCBL: "Zoroastrian Co-operative Bank",
    MHCB: "Mizuho Bank",
    NJBK: "Nav Jeevan Co-operative Bank",
    BNPA: "BNP Paribas Bank",
    CRUB: "Shri Chhatrapati Rajashri Shahu Urban Co-operative Bank",
    NCUB: "Nilambur Co-operative Urban Bank",
    VVSB: "Vasai Vikas Sahakari Bank",
    TSSB: "Satara Sahakari Bank",
    PUSD: "Pusad Urban Co-operative Bank",
    KOEX: "KEB Hana Bank",
    IDFB: "IDFC FIRST Bank",
    JTSC: "Janatha Seva Co-operative Bank",
    SABR: "SBER Bank",
    QNBA: "Qatar National Bank",
    BKID: "Bank of India",
    APGV: "Andhra Pradesh Grameena Vikas Bank",
    DBSS: "Development Bank of Singapore",
    ORBC: "Oriental Bank of Commerce",
    CRES: "Credit Suisse AG",
    JIOP: "Jio Payments Bank",
    CITI: "CITI Bank",
    CHAS: "JP Morgan Chase Bank NA",
    NKGS: "NKGSB Co-operative Bank",
    DLXB: "Dhanlaxmi Bank",
    DCUB: "Darussalam Co-operative Urban Bank",
    APGB: "Andhra Pragathi Grameena Bank",
    IDIB: "Indian Bank",
    FDRL: "Federal Bank",
    SPCB: "Surat People's Co-operative Bank",
    KDCB: "Kozhikode District Co-operative Bank",
    AUBL: "AU Small Finance Bank",
    TJSB: "TJSB Sahakari Bank",
    VCOB: "The Vijay Co-operative Bank",
    IPOS: "India Post Payments Bank",
    ZSBL: "Zila Sahakari Bank Ghaziabad",
    KUCB: "Karad Urban Co-operative Bank",
    UCBA: "UCO Bank",
    CIUB: "City Union Bank",
    TGMB: "Tumkur Grain Merchant's Co-operative Bank",
    JSBL: "Janakalyan Sahakari Bank",
    RBIP: "Reserve Bank of India",
    RBIN: "Reserve Bank Of India",
    SIDC: "Sindhudurg District Central Co-operative Bank",
    ANDB: "Andhra Bank",
    JSBP: "Janata Sahakari Bank (Pune)",
    SHBK: "Shinhan Bank",
    HPSC: "Himachal Pradesh State Co-operative Bank",
    RBIS: "Reserve Bank of India",
    NICB: "New India Co-operative Bank",
    PMEC: "Prime Co-operative Bank",
    COAS: "Coastal Local Area Bank",
    MSLM: "Muslim Co-operative Bank",
    BNSB: "Bhagini Nivedita Sahakari Bank Pune",
    DMKJ: "Dmk Jaoli Bank",
    DICG: "Deposit Insurance and Credit Guarantee Corporation",
    ABNA: "Royal Bank of Scotland N.V.",
    KKBK: "Kotak Mahindra Bank",
    AUCB: "Almora Urban Co-operative Bank",
    URBN: "Urban Co-operative Bank Perinthalmanna",
    KSBK: "Kerala State Co-operative Bank",
    SBIN: "State Bank of India",
    THRS: "Thrissur District Co-operative Bank",
    KCCB: "Kalupur Commercial Co-operative Bank",
    AMCB: "Ahmedabad Mercantile Co-operative Bank",
    CRGB: "Chhattisgarh Rajya Gramin Bank",
    ICIC: "ICICI Bank",
    BOTM: "MUFG Bank",
    TAUB: "Ankola Urban Co-operative Bank",
    NVNM: "Navnirman Co-operative Bank",
    COSB: "Cosmos Co-operative Bank",
    KVGB: "Karnataka Vikas Grameena Bank",
    ORCB: "Odisha State Co-operative Bank",
    AMDN: "Ahmednagar Merchants Co-operative Bank",
    PSBL: "Pavana Sahakari Bank",
    SMNB: "Smriti Nagrik Sahakari Bank",
    KANG: "Kangra Co-operative Bank",
    JJSB: "Jalgaon Janata Bank",
    MAHB: "Bank of Maharashtra",
    RNSB: "Rajkot Nagarik Sahakari Bank",
    MAHG: "Maharashtra Gramin Bank",
    SUNB: "Surat National Co-operative Bank",
    CORP: "Corporation Bank",
    BBKM: "Bank of Bahrein and Kuwait",
    SNBK: "Saraspur Nagrik Co-operative Bank",
    KOLH: "Kolhapur Urban Co-operative Bank",
    CNRB: "Canara Bank",
    IOBA: "Indian Overseas Bank",
    MSNU: "Mehsana Urban Co-operative Bank",
    ESFB: "Equitas Small Finance Bank",
    EIBI: "Export Import Bank of India",
    KJSB: "Kalyan Janata Sahakari Bank",
    MUBL: "Municipal Co-operative Bank",
    BOFA: "Bank of America",
    CBIN: "Central Bank of India",
    ADCC: "Akola District Central Co-operative Bank",
    GDCB: "Gadchiroli District Central Co-operative Bank",
    KLGB: "Kerala Gramin Bank",
    SVSH: "Shree Veershaiv Co-operative Bank",
    UTIB: "Axis Bank",
    ASBL: "Apna Sahakari Bank",
    FINO: "Fino Payments Bank",
    JASB: "Janaseva Sahakari Bank (Borivli)",
    KSCB: "Karnataka State Co-operative Apex Bank",
    JSFB: "Jana Small Finance Bank",
    TPSC: "Punjab State Co-operative Bank",
    MVCB: "Sir M Visvesvaraya Co-operative Bank",
    NGSB: "Nagpur Nagarik Sahakari Bank",
    PJSB: "Gopinath Patil Parsik Janata Sahakari Bank",
    SAHE: "Sahebrao Deshmukh Co-operative Bank",
    VSBL: "Vishweshwar Sahakari Bank",
    BMCB: "Bombay Mercantile Co-operative Bank",
    HVBK: "Woori Bank",
    NOSC: "Bank of Nova Scotia",
  },
  POPULAR: {
    BARB: "Bank of Baroda",
    CITI: "CITI Bank",
    KARB: "Karnataka Bank",
    ICIC: "ICICI Bank",
    IDIB: "Indian Bank",
    HDFC: "HDFC Bank",
    HSBC: "Hongkong & Shanghai Banking Corporation",
    KBKB: "Kookmin Bank",
  },
};
