export enum ACTION {
  ON_CHANGE_SLIDER = "ON_CHANGE_SLIDER",
  GO_BACK = "GO_BACK",
  GO_CONFIRM_PLEDGE = "GO_CONFIRM_PLEDGE",
  EDIT_PORTFOLIO = 'EDIT_PORTFOLIO'
}
export type TestActionPayload = {};
