export const ROUTE = {
  PHONE_NUMBER: "PHONE_NUMBER",
  ENTER_EMAIL: "ENTER_EMAIL",
  OTP_VERIFY: "OTP_VERIFY",
  EMAIL_VERIFY: "EMAIL_VERIFY",
  KYC_PAN_VERIFICATION: "KYC_PAN_VERIFICATION",
  PAN_CONFIRM_NAME: "PAN_CONFIRM_NAME",
  MF_PLEDGING: "MF_PLEDGING",
};

// "KYC_PHOTO_VERIFICATION": "NOT_STARTED",
//     "MF_PLEDGING": "NOT_STARTED",
//     "CREDIT_APPROVAL": "NOT_STARTED",
//     "KYC_AADHAAR_VERIFICATION": "NOT_STARTED",
//     "MANDATE_SETUP": "NOT_STARTED",
//     "KYC_CKYC": "NOT_STARTED",
//     "KYC_PAN_VERIFICATION": "NOT_STARTED",
//     "AGREEMENT_SIGN": "NOT_STARTED",
//     "BANK_ACCOUNT_VERIFICATION": "NOT_STARTED"
