export enum ACTION {
  EDIT_SLIDER_AMOUNT = "EDIT_SLIDER_AMOUNT",
  SLIDER_AMOUNT_ONCHANGE = "SLIDER_AMOUNT_ONCHANGE",
  DISABLE_CONTINUE = "DISABLE_CONTINUE",
  ENABLE_CONTINUE = "ENABLE_CONTINUE",
  GET_EDIT_AMOUNT_ONLOAD = "GET_EDIT_AMOUNT_ONLOAD"
}
export type UpdateMobileNumber = { value: string; targetWidgetId: string };
